### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by matteoskebby** [lesstif/gitlab-jira-integration#11]
Hello, 
thank you for the nice project. 
I have no chance to install your application from scratch with just a composer install. 

PHP Fatal error:  Class 'Slim\Slim' not found in /opt/www/gitlab-jira-integration/index.php on line 9
PHP Fatal error:  Class 'Slim\Logger\DateTimeFileWriter' not found in /opt/www/gitlab-jira-integration/index.php on line 14
PHP Fatal error:  Class 'Dotenv\Dotenv' not found in /opt/www/gitlab-jira-integration/index.php on line 199

Am i missing something ?

**Comment by lesstif** [comment]
Slim framework removed at 1 month ago.
you seems like using past version.
Running below command and try again.

``` sh
git checkout master
git pull origin master
composer install
php artisan serve
```

**Comment by matteoskebby** [comment]
Ok, I think the problem is that i'm referencing ./ as the root where an index.php with slim is present, rather then referencing the public folder where another index is present
