### ISSUE TITLE
Installation failed on 'composer' step

### ISSUE THREAD

**Issue by lrozenblyum** [lesstif/gitlab-jira-integration#3]
Hello!
We cannot install the plug-in.

During execution of command

``` shell
composer require lesstif/gitlab-jira-integration dev-master
```

we received an exception:

 composer require lesstif/gitlab-jira-integration dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package lesstif/gitlab-jira-integration could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by lesstif** [comment]
thanks you for your feedback.

Documentation is incorrect. This project standalone app then can't install via composer.
I'm completed rewritten code and publish new release.
Would you re-installing using new release?

**Comment by lrozenblyum** [comment]
Hello sure I'll try the new release ! (hopefully as early as possible next week)
