### ISSUE TITLE
failed on executing

### ISSUE THREAD

**Issue by tabsl** [lesstif/gitlab-jira-integration#5]
he, installation was easy, thanky!

but now, if i add an commit in gitlab, i get an error in lumen app :-(

[2015-07-17 12:20:25] lumen.DEBUG: hook received from
[2015-07-17 12:20:25] lumen.INFO: eventType : Push Hook
[2015-07-17 12:20:25] lumen.DEBUG: Commit : {
    "id": "94ff21bd817b2a10d82b61842c03965eaa06998b",
    "message": "TICKET-50 test 2\n",
    "timestamp": "2015-07-17T14:12:55+02:00",
    "url": "https:\/\/xxx\/myproject\/commit\/94ff21bd817b2a10d82b61842c03965eaa06998b",
    "author": {
        "name": "name",
        "email": "email"
    }
}
[2015-07-17 12:20:25] lumen.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/gitlab-jira-integration/app/Http/Controllers/GitlabController.php:112
Stack trace:

```
#0 /var/www/gitlab-jira-integration/app/Http/Controllers/GitlabController.php(112): Laravel\Lumen\Application->Laravel\Lumen\{closure}(8, 'Trying to get p...', '/var/www/gitlab...', 112, Array)
#1 /var/www/gitlab-jira-integration/app/Http/Controllers/GitlabController.php(76): App\Http\Controllers\GitlabController->needTransition('PROUDCOM-50 tes...', NULL)
#2 /var/www/gitlab-jira-integration/app/Http/Controllers/GitlabController.php(38): App\Http\Controllers\GitlabController->pushHook(Object(Illuminate\Http\Request))
#3 [internal function]: App\Http\Controllers\GitlabController->hookHandler(Object(Illuminate\Http\Request))
#4 /var/www/gitlab-jira-integration/vendor/illuminate/container/Container.php(502): call_user_func_array(Array, Array)
#5 /var/www/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1328): Illuminate\Container\Container->call(Array, Array)
#6 /var/www/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1293): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#7 /var/www/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1264): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\GitlabController), 'hookHandler', Array)
#8 /var/www/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1232): Laravel\Lumen\Application->callControllerAction(Array)
#9 /var/www/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1217): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#10 /var/www/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1138): Laravel\Lumen\Application->handleFoundRoute(Array)
#11 /var/www/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1370): Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#12 /var/www/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1144): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 /var/www/gitlab-jira-integration/vendor/laravel/lumen-framework/src/Application.php(1084): Laravel\Lumen\Application->dispatch(NULL)
#14 /var/www/gitlab-jira-integration/public/index.php(28): Laravel\Lumen\Application->run()
#15 /var/www/gitlab-jira-integration/server.php(12): require_once('/var/www/gitlab...')
```

**Comment by lesstif** [comment]
Would you attach a posted file(storage/app/Push-Hook.json)?

**Comment by proudcommerce** [comment]
{
    "before": "66f0868e12db253ec66507acac9f34d66dd24039",
    "after": "94ff21bd817b2a10d82b61842c03965eaa06998b",
    "ref": "refs\/heads\/master",
    "user_id": 2,
    "user_name": "Tobias Merkl",
    "project_id": 23,
    "repository": {
        "name": "myproject.com",
        "url": "git@gitlab:myproject.git",
        "description": "",
        "homepage": "https:\/\/gitlab/myproject"
    },
    "commits": [
        {
            "id": "94ff21bd817b2a10d82b61842c03965eaa06998b",
            "message": "XXX-50 test 2\n",
            "timestamp": "2015-07-17T14:12:55+02:00",
            "url": "https:\/\/gitlab/myproject\/commit\/94ff21bd817b2a10d82b61842c03965eaa06998b",
            "author": {
                "name": "Tobias Merkl",
                "email": "merkl@proudsourcing.de"
            }
        },
        {
            "id": "b3a92eb8219741b1ada7a5e4efbd7a11037c4ace",
            "message": "XXX-50 test commit\n",
            "timestamp": "2015-07-17T14:08:04+02:00",
            "url": "https:\/\/gitlab/myproject\/commit\/b3a92eb8219741b1ada7a5e4efbd7a11037c4ace",
            "author": {
                "name": "Tobias Merkl",
                "email": "merkl@proudsourcing.de"
            }
        },
        {
            "id": "66f0868e12db253ec66507acac9f34d66dd24039",
            "message": "Merge branch 'stage'\n\n\* stage:\n  my new modul\n",
            "timestamp": "2015-05-19T17:06:58+02:00",
            "url": "https:\/\/gitlab/myproject\/commit\/66f0868e12db253ec66507acac9f34d66dd24039",
            "author": {
                "name": "Tobias Merkl",
                "email": "tobias@merkl.eu"
            }
        }
    ],
    "total_commits_count": 3
}

**Comment by proudcommerce** [comment]
i updated git repo, but getting the same error :-(

**Comment by lesstif** [comment]
Sorry, I can't reproduce same error locally.

Could you please take the following steps.
1. Check repository revision is same result.
   
   ``` sh
   $ git rev-parse master
   1434e9beb00dace4436ca523ef934ea8348cdb69
   ```
2. restart gitlab-jira-integration app.
   
   ``` sh
   ## pkill command is only available on linux .
   pkill php 
   php artisan serve --port 9000
   ```
3. Run following command locally and  confirm that you can reproduce the problem.
   
   ``` sh
   $ curl -X POST -d@storage/app/Push-Hook.json http://localhost:9000/gitlab/hook 
   ```

Finally, please attach storage/logs/lumen.log.

thanks.

![image](https://cloud.githubusercontent.com/assets/404534/8777576/bf17855a-2f33-11e5-9145-784f39cda67e.png)

**Comment by proudcommerce** [comment]
$ git rev-parse master
1434e9beb00dace4436ca523ef934ea8348cdb69

lumen.log:
http://screens.tabsl.eu/9b850542f47ddda72909cefa97ba00.png

**Comment by lesstif** [comment]
I supposed that all hook's had commit message.

I modified the foreach condition code(https://github.com/lesstif/gitlab-jira-integration/commit/f978cbfb7628b28a55e92d958f9f149292397e00), so it fixed this circumstance, But jira integration needs special commit messages.

**Comment by proudcommerce** [comment]
now its working, thanks!
- typo in config.integration.json
- curl missing
- gitlab test hooks are not working
